### numpy

In [1]:
import numpy as np
np.__version__

'1.25.2'

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [3]:
l = [11,22,33,44,55,66]
ar = np.array(l)
print(ar)
print(type(ar))

[11 22 33 44 55 66]
<class 'numpy.ndarray'>


In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [8]:
tup =(1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))
print(ar.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [9]:
arr = np.array(10)
print(arr)
print(arr.ndim)

10
0


In [12]:
arr = np.array((11,22,33,44,55,66))
print(arr)
print(type(arr))
print(arr.ndim)


[11 22 33 44 55 66]
<class 'numpy.ndarray'>
1


In [38]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.ndim)
# access  element 1-D array
print('elements present as 4 th index',arr[5])
print('elements present as 3 th index',arr[3])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
elements present as 4 th index 6
elements present as 3 th index 4


In [25]:
arr =[[1,2,3,4],[5,6,7,8]]
ar = np.array(arr)
print(ar)
print(ar.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [31]:
ar = [[1,2,3]]
arr = np.array(ar)
print(arr)
print(arr.ndim)


[[1 2 3]]
2


In [5]:
import numpy as np
np.__version__

'1.25.2'

In [8]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [11]:
tup = ((1,2,3,4,5,6,7))
arr = np.array(tup)
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1


In [16]:
arr = np.array(20)
print(arr)
print(arr.ndim)
arr = [[11,22,33,44,55,66]]
ar = np.array(arr)
print(ar)
print(ar.ndim)
arr = ((11,22,33,44,55,66))
ar = np.array(arr)
print(ar)
print(ar.ndim)

arr = [[1,2,3,4],[5,6,7,8]]
ar = np.array(arr)
print(ar)
print(ar.ndim)

20
0
[[11 22 33 44 55 66]]
2
[11 22 33 44 55 66]
1
[[1 2 3 4]
 [5 6 7 8]]
2


In [26]:
print(arr)
print(arr[0])
print(arr[0][1])
print(arr[1])
print(arr[1][2])



[[1, 2, 3, 4], [5, 6, 7, 8]]
[1, 2, 3, 4]
2
[5, 6, 7, 8]
7


In [28]:
print(ar)
print(ar.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


### 3- D Array

In [34]:
ar = [[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]]
print(ar)
print(type(ar))
arr = np.array(ar)
print(arr)
print(type(arr))
print(arr.ndim)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [11, 12, 13]]]
<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
<class 'numpy.ndarray'>
3


In [42]:
# one way
print(arr)
print(arr[1])
print(arr[0])
print(arr[0][0])
print(arr[0][0][1])
# another way
print(arr[1])
print(arr[0,0])
print(arr[0,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
[[ 7  8  9]
 [11 12 13]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
2
[[ 7  8  9]
 [11 12 13]]
[1 2 3]
3


In [44]:
a = np.array(10)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### create an n dimensinal array 


In [48]:
arr = np.array([1,2,3,4,5], ndmin =5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [49]:
arr = np.array([11,22,33,44,55], ndmin = 7)
print(arr)
print(arr.ndim)

[[[[[[[11 22 33 44 55]]]]]]]
7


### 1 - D array

In [50]:
arr = ([1,2,3,4,5])
ar = np.array(arr)
print(ar)
print(ar.ndim)

[1 2 3 4 5]
1


In [55]:
print(ar)
print(ar[0])
print(ar[4])

[1 2 3 4 5]
1
5


In [56]:
ar = ([[1,2,3],[4,5,6]])
arr = np.array(ar)
print(arr)
print(arr.ndim)


[[1 2 3]
 [4 5 6]]
2


In [65]:
print(arr)
print(arr[0])
print(arr[1])
print(arr[0][2])
print(arr[1][1])
print(arr[0,1])
print(arr[1,2])

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
3
5
2
6


In [66]:
arr = ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar = np.array(arr)
print(ar)
print(ar.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [76]:
print(ar)
print(ar[0])
print(ar[1])
print(ar[0][0])
print(ar[0][1][2])
print(ar[1][0])
print(ar[1][1][2])
print(ar[0,0])
print(ar[1,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
6
[7 8 9]
12
[1 2 3]
9


In [77]:
a = np.array(100)
b = np.array([1,2,3,4])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [78]:
arr = np.array([11,22,33,44,55], ndmin = 6)
print(arr)
print(arr.ndim)

[[[[[[11 22 33 44 55]]]]]]
6


In [79]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [80]:
l = [11,22,33,44,55,66]
arr = np.array(l)
print(arr)
print(type(arr))

[11 22 33 44 55 66]
<class 'numpy.ndarray'>


In [81]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [84]:
tup = (11,22,33,44,55,66)
arr = np.array(tup)
print(arr)
print(type(arr))
print(arr.ndim)

[11 22 33 44 55 66]
<class 'numpy.ndarray'>
1


### 0-D Array

In [87]:
arr = np.array(20)
print(arr)
print(arr.ndim)

20
0


### 1 - D Array

In [89]:
arr = ([1,2,3,4,5,6,7])
ar = np.array(arr)
print(arr)
print(type(ar))
print(ar.ndim)

[1, 2, 3, 4, 5, 6, 7]
<class 'numpy.ndarray'>
1


In [91]:
print(ar)
print(ar[3])

[1 2 3 4 5 6 7]
4


### 2 - D Array

In [94]:
arr = ([[1,2,3,4],[5,6,7,8]])
ar = np.array(arr)
print(ar)
print(type(ar))
print(ar.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [99]:
print(ar)
print(ar[1])
print(ar[0])
print(ar[0][1])
print(ar[1][2])

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]
[1 2 3 4]
2
7


### 3-D Array

In [100]:
arr = ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar = np.array(arr)
print(ar)
print(type(ar))
print(ar.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


In [109]:
print(ar)
print(ar[0])
print(ar[1])
print(ar[0][1])
print(ar[1][1][2])
print(ar[0,0,2])
print(ar[1,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[4 5 6]
12
3
11


In [110]:
a = np.array(100)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [112]:
arr = np.array([1,2,3,4,5], ndmin = 3)
print(arr)
print(arr.ndim)

[[[1 2 3 4 5]]]
3


In [113]:
arr = np.array([10,20,30,40,60], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[10 20 30 40 60]]]]]
5


In [1]:
import numpy as np
np.__version__

'1.25.2'

In [2]:
arr = np.array([11,22,33,44,55,66])
print(arr)
print(type(arr))

[11 22 33 44 55 66]
<class 'numpy.ndarray'>


In [3]:
l = [1,2,3,4,5,6]
arr = np.array(l)
print(arr)
print(type(arr))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr[4])

[1 2 3 4 5]
1
5


In [9]:
arr = np.array(20)
print(arr)
print(arr.ndim)

20
0


In [19]:
arr = ([[1,2,3],[4,5,6]])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(ar)
print(ar[0])
print(ar[1])
print(ar[0][2])
print(ar[1][2])
print(ar[0,0])
print(ar[1,1])

[[1 2 3]
 [4 5 6]]
2
[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
3
6
1
5


In [28]:
arr = ([[[11,22,33],[44,55,66]],[[77,88,99],[100,101,102]]])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(ar[0])
print(ar[1])
print(ar[0][0])
print(ar[0][1][2])
print(ar[1][0][1])
print(ar[0,0,1])
print(ar[0,1,2])

[[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [100 101 102]]]
3
[[11 22 33]
 [44 55 66]]
[[ 77  88  99]
 [100 101 102]]
[11 22 33]
66
88
22
66


In [29]:
a = np.array(100)
b = np.array([11,22,33,44,55])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [30]:
arr = np.array([1,2,3,4,5], ndmin = 4)
print(arr)
print(arr.ndim)

[[[[1 2 3 4 5]]]]
4


### Numpy Array Slicing

In [35]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(len(arr))
print(arr[0:7])
print(arr[4:])

[1 2 3 4 5 6 7]
7
[1 2 3 4 5 6 7]
[5 6 7]


### nagetive indicies

In [39]:
arr =np.array([1,2,3,4,5,6,7,8])
print(arr)
print(arr[-1])
print(arr[-8])
print(arr[-4:-2])
print(arr[-2:-5])

[1 2 3 4 5 6 7 8]
8
1
[5 6]
[]


### step value

In [45]:
print(arr)
print(arr[0:7:3])
print(arr[::2])
print(arr[:6:2])
print(arr[0:6:2])

[1 2 3 4 5 6 7 8]
[1 4 7]
[1 3 5 7]
[1 3 5]
[1 3 5]


### 2 - D Array

In [71]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0])
print(arr[1])
print(arr[1,2])
print(arr[1, 1:3])
print(arr[0,3])
print(arr[0:1,0:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[ 6  7  8  9 10]
8
[7 8]
4
[[1 2 3 4]]


In [55]:
print(arr)
print(arr[0:2,0:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [6 7 8]]


In [70]:
print(arr)
print(arr[0:2,0:3])
print(arr[0:2,0:2])

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
[[ 1  2  3]
 [10 20 30]]
[[ 1  2]
 [10 20]]


### 3 - D array slicing

In [73]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size)
print(arr.shape)
print(arr[0:2,1:3])
print(arr[0:1,1:3])

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15
(3, 5)
[[ 2  3]
 [20 30]]
[[2 3]]


### numpy array silcing

In [88]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(len(arr))
print(arr[0:4])
print(arr[0:6])
print(arr[:5])
print(arr[:3])
print(arr[3:])
print(arr[-4])
print(arr[-1])
print(arr[-5:-1])
print(arr[-6:-1])
print(arr[-1:])
print(arr[-8:-2])
print(arr[-2:-1])

[1 2 3 4 5 6 7 8 9]
9
[1 2 3 4]
[1 2 3 4 5 6]
[1 2 3 4 5]
[1 2 3]
[4 5 6 7 8 9]
6
9
[5 6 7 8]
[4 5 6 7 8]
[9]
[2 3 4 5 6 7]
[8]


### step value

In [109]:
print(arr)
print(arr[0:9:2])
print(arr[1:6:3])
print(arr[4:8:2])
print(arr[1:8:6])
print(arr[0:8:8])
print(arr[:6:2])
print(arr[: : 2])
print(arr[::4])
print(arr[:3:1])
print(arr[0:3:1])
print(arr[1:4:])
print(arr[5:7:1])
print(arr[2:4:1])
print(arr[7:9:1])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[2 5]
[5 7]
[2 8]
[1]
[1 3 5]
[1 3 5 7 9]
[1 5 9]
[1 2 3]
[1 2 3]
[2 3 4]
[6 7]
[3 4]
[8 9]


### slicing 2 - D Array

In [124]:
arr = np.array([[11,22,33,44,55],[66,77,88,99,100]])
print(arr)
print(arr[0])
print(arr[1])
print(arr[1,2])
print(arr[0,0:3])
print(arr[1,0:4])
print(arr[0:1,0:3])
print(arr[::-1])


[[ 11  22  33  44  55]
 [ 66  77  88  99 100]]
[11 22 33 44 55]
[ 66  77  88  99 100]
88
[11 22 33]
[66 77 88 99]
[[11 22 33]]
[[ 66  77  88  99 100]
 [ 11  22  33  44  55]]


### 2 - D Array

In [156]:
import numpy as np
ar = ([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr = np.array(ar)
print(arr)
print(arr.ndim)
print(arr[:1])
print(arr[:-3])
print(arr[0:2,0:3])
print(arr[1:3,1:3])
print(arr[1:3,])
print(arr[2:-1])
print(arr[1:3,0:2])
print(arr[1:3,0:1])
print(arr[:,1:3])
print(arr[1:3,1])
print(arr[0:2,2])
print(arr[0:3,2])
print(arr[1:3,:1])
print(arr[1:3,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2
[[1 2 3 4]]
[[1 2 3 4]]
[[1 2 3]
 [5 6 7]]
[[ 6  7]
 [10 11]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 9 10 11 12]]
[[ 5  6]
 [ 9 10]]
[[5]
 [9]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[ 6 10]
[3 7]
[ 3  7 11]
[[5]
 [9]]
[ 6 10]


### 3 - D Array

In [197]:
ar = ([[[10,20,30],[40,50,60],[70,80,90],[100,110,120]]])
arr = np.array(ar)
print(arr)
print(arr[0])
print(arr[0,1])
print(arr[0,1,2])
print(arr[0:1])
print(arr[0:2,1])
print(arr[0:3,2])
print(arr[0:3])
print(arr[0,3])
print(arr[0,0,1])
print(arr[0:3])
print(arr[0,1,1])
print(arr[0:1:2])
print(arr[0:1:2])
print(arr[0:1:1])
print(arr[0:1])
print(arr[0:1])
print(arr[0:2,0:2])
print(arr[:1,0:2])

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[40 50 60]
60
[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
[[40 50 60]]
[[70 80 90]]
[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
[100 110 120]
20
[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
50
[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
[[[10 20 30]
  [40 50 60]]]
[[[10 20 30]
  [40 50 60]]]


### date types numpy array

In [5]:
import numpy as np
# int
arr = np.array([11,22,33,44])
print(arr)
print(arr.dtype)
# string
arr = np.array(['aa','bb','cc'])
print(arr)
print(arr.dtype)
arr = np.array(['apple','kiwi','lemon','mango'])
print(arr)
print(arr.dtype)
arr = np.array(['blue','pink','red','grey'])
print(arr)
print(arr.dtype)

[11 22 33 44]
int32
['aa' 'bb' 'cc']
<U2
['apple' 'kiwi' 'lemon' 'mango']
<U5
['blue' 'pink' 'red' 'grey']
<U4


In [18]:
### creting array with a defined data type
arr = np.array([1,2,3,4], dtype = 'i')
print(arr)
print(arr.dtype)
arr = np.array([11,22,33,44],dtype = 'float')
print(arr)
print(arr.dtype)
arr = np.array([1,2,3,4,5,6],dtype = 'f')
print(arr)
print(arr.dtype)
arr = np.array([1,2,3,4,5],dtype = 'i4')
print(arr)
print(arr.dtype)
arr = np.array([11,22,33,44],dtype = 'f4')
print(arr)
print(arr.dtype)
arr = np.array(['1','2','3'],dtype = 'int')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32
[11. 22. 33. 44.]
float64
[1. 2. 3. 4. 5. 6.]
float32
[1 2 3 4 5]
int32
[11. 22. 33. 44.]
float32
[1 2 3]
int32


### float to int

In [20]:
# float to int
arr = np.array([1.1,2.2,3.3,4.4,5.5])
newarr = arr.astype('i')
print(arr)
print(newarr)
print(newarr.dtype)

[1.1 2.2 3.3 4.4 5.5]
[1 2 3 4 5]
int32


In [22]:
# int to bool
arr = np.array([1,0,3])
newarr = arr.astype('bool')
print(arr)
print(newarr)
print(newarr.dtype)

[1 0 3]
[ True False  True]
bool


### copy

In [25]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
print(x)
x[1] = 20
print(x)
print(arr)

[1 2 3 4 5]
[ 1 20  3  4  5]
[1 2 3 4 5]


In [27]:
arr = np.array([11,22,33,44])
x = arr.view()

print(x)
x[1] = 100
print(x)
print(arr)


[11 22 33 44]
[ 11 100  33  44]
[ 11 100  33  44]


In [28]:
arr = np.array([1,2,3,4,5,6])
a = arr.copy()
b = arr.view()
print(a.base)
print(b.base)

None
[1 2 3 4 5 6]


### numpy array

In [29]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [30]:
ar = ([11,22,33,44,55,66,77,88])
arr = np.array(ar)
print(arr)
print(type(arr))

[11 22 33 44 55 66 77 88]
<class 'numpy.ndarray'>


In [32]:
arr =(1,2,3,4,5)
ar = np.array(arr)
print(ar)
print(type(ar))
print(ar.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [33]:
arr =np.array(10)
print(arr)
print(arr.ndim)

10
0


In [41]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)
print(arr[2])
print(arr[5])
print(arr[0:4])
print(arr[1:5])


[1 2 3 4 5 6]
1
3
6
[1 2 3 4]
[2 3 4 5]


In [59]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[0])
print(arr[1])
print(arr[1][3])
print(arr[1,2])
print(arr[0:2])
print(arr[0:3,1:3])
print(arr[2,3])
print(arr[0:3,2:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
2
[1 2 3 4]
[5 6 7 8]
8
7
[[1 2 3 4]
 [5 6 7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]
12
[[ 3]
 [ 7]
 [11]]


In [74]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)
print(arr.ndim)
print(arr[0])
print(arr[1])
print(arr[0,1])
print(arr[1,0])
print(arr[1,1])
print(arr[0:3,])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [75]:
arr = np.array([1,2,3,4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [76]:
arr =np.array([1.1,1.2,1.3,1.4])
print(arr)
print(arr.dtype)

[1.1 1.2 1.3 1.4]
float64


In [77]:
arr = np.array(['apple','kiwi','lemon','grey'])
print(arr)
print(arr.dtype)

['apple' 'kiwi' 'lemon' 'grey']
<U5


In [78]:
arr = np.array(['aa','bb','cc'])
print(arr)
print(arr.dtype)

['aa' 'bb' 'cc']
<U2


In [80]:
arr = np.array([1,2,3,4], dtype = 'i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [81]:
arr = np.array([1.2,2.2,3.4,5.6], dtype = 'f')
print(arr)
print(arr.dtype)

[1.2 2.2 3.4 5.6]
float32


In [82]:
arr = np.array([1,2,3,4,5],dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [83]:
arr = np.array(['1','2','3'],dtype = 'i')
print(arr)
print(arr.dtype)

[1 2 3]
int32


In [87]:
arr = np.array(['11','22','33','44'],dtype = 'i4')
print(arr)
print(arr.dtype)

[11 22 33 44]
int32


In [88]:
arr = np.array([1.1,1.2,1.3,1.4])
newarr = arr.astype('i')
print(arr)
print(newarr)
print(newarr.dtype)

[1.1 1.2 1.3 1.4]
[1 1 1 1]
int32


In [89]:
arr = np.array([11,22,33,44])
newarr = arr.astype('f')
print(arr)
print(newarr)
print(newarr.dtype)

[11 22 33 44]
[11. 22. 33. 44.]
float32


In [3]:
import numpy as np
arr = np.array([1,0,3])
newarr = arr.astype('bool')
print(arr)
print(newarr)
print(newarr.dtype)
arr = np.array([1.1,0,2,3])
newarr = arr.astype('bool')
print(arr)
print(newarr)

print(newarr.dtype)

[1 0 3]
[ True False  True]
bool
[1.1 0.  2.  3. ]
[ True False  True  True]
bool


### copy


In [4]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
x[2]= 20
print(x)
print(arr)

[ 1  2 20  4  5]
[1 2 3 4 5]


In [5]:
arr = np.array([1,2,3,4,5])
x = arr.view()
x[1] = 100
print(x)
print(arr)

[  1 100   3   4   5]
[  1 100   3   4   5]


In [6]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [7]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
arr = np.array([11,22,33,44,55])
print(arr)
print(type(arr))
print(arr.ndim)

[11 22 33 44 55]
<class 'numpy.ndarray'>
1


In [11]:
arr = ([1,2,3,4,5])
ar = np.array(arr)
print(ar)
print(ar.ndim)

[1 2 3 4 5]
1


In [12]:
l = (1,2,3,4,5,6,7)
arr= np.array(l)
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7]
1


In [13]:
tup = (10,20,30)
ar = np.array(tup)
print(ar)
print(type(ar))
print(ar.ndim)

[10 20 30]
<class 'numpy.ndarray'>
1


In [69]:
# 0-d array
arr = np.array(10)
print(arr)
print(arr.ndim)
# 1-d array
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr[1])
print(arr[0:3])
print(arr[-1])
print(arr[-4:-1])
# 2 - d array
arr = ([11,22,33,44,],[10,20,30,40])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(arr[0])
print(arr[1])
print(arr[0][2])
print(arr[0][3])
print(arr[1][2])
print(arr[0:2])
print(arr[0:1])
print(arr[0:2])
print(arr[0][2])
# 2 -d array
arr = ([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(ar[0])
print(ar[1])
print(ar[0][1])
print(ar[0:2,0:1])
print(ar[0:2,1:2])
# 3 - d array
arr = ([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(ar[0])
print(ar[1])
print(ar[0][0])
print(ar.size)
print(ar.shape)
print(ar[::2])
print(ar[:1])
print(ar[-4:-1])

10
0
[1 2 3 4 5]
1
2
[1 2 3]
5
[2 3 4]
[[11 22 33 44]
 [10 20 30 40]]
2
[11, 22, 33, 44]
[10, 20, 30, 40]
33
44
30
([11, 22, 33, 44], [10, 20, 30, 40])
([11, 22, 33, 44],)
([11, 22, 33, 44], [10, 20, 30, 40])
33
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2
[1 2 3 4]
[5 6 7 8]
2
[[1]
 [5]]
[[2]
 [6]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[1 2 3 4]
16
(2, 2, 4)
[[[1 2 3 4]
  [5 6 7 8]]]
[[[1 2 3 4]
  [5 6 7 8]]]
[[[1 2 3 4]
  [5 6 7 8]]]


In [73]:
arr = np.array([1,2,3,4,5],ndmin = 5)
print(arr)


[[[[[1 2 3 4 5]]]]]


In [74]:
print(arr)

[[[[[1 2 3 4 5]]]]]


In [75]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [84]:
print(arr)
print(arr[0:3])
print(arr[0:4:2])
print(arr[::2])
print(arr[0::3])
print(arr[:6:2])
print(arr[2:5])
print(arr[1:6:2])

[1 2 3 4 5 6 7 8]
[1 2 3]
[1 3]
[1 3 5 7]
[1 4 7]
[1 3 5]
[3 4 5]
[2 4 6]


In [112]:
# int 
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(arr.ndim)
arr = np.array([1.1,1.2,1.3,1.4])
print(arr)
print(arr.dtype)
arr = np.array([1,2,3,4,5,6,7,], dtype = 'i4')
print(arr)
print(arr.dtype)
arr = np.array(['aa','bb','cc','dd'])
print(arr)
print(arr.dtype)
arr = np.array(['lemon','kiwi','banana'])
print(arr)
print(arr.dtype)
arr = np.array([11,22,33,44,55], dtype = 'int')
print(arr)
print(arr.dtype)
arr = np.array([1.2,2.2,3.3,4.4,5.5], dtype = 'f')
print(arr)
print(arr.dtype)
arr = np.array([1,2,3,4,5,6],dtype = 'i4')
print(arr)
print(arr.dtype)
arr = np.array(['11','22','33','44'],dtype = 'i')
print(arr)
print(arr.dtype)
# int to float
arr = np.array([1,2,3,4,5,6,7])
newarr = arr.astype('float')
print(arr)
print(newarr)
print(newarr.dtype)
# float to int
arr = np.array([1.1,1.2,2.2,3.4,4.5,6.7])
a = arr.astype('int')
print(arr)
print(a)
print(a.dtype)
# int to bool
arr = np.array([1,3,0,5])
x = arr.astype('bool')
print(arr)
print(x)
print(x.dtype)
# copy
arr = np.array([1,2,3,4,5])
x = arr.copy()
x[0]= 100

print(x)
print(arr)
# view
arr = np.array([1,2,3,4,5,6])
x = arr.view()
x[2] = 200
print(arr)
print(x)
# base
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

[1 2 3 4 5]
int32
1
[1.1 1.2 1.3 1.4]
float64
[1 2 3 4 5 6 7]
int32
['aa' 'bb' 'cc' 'dd']
<U2
['lemon' 'kiwi' 'banana']
<U6
[11 22 33 44 55]
int32
[1.2 2.2 3.3 4.4 5.5]
float32
[1 2 3 4 5 6]
int32
[11 22 33 44]
int32
[1 2 3 4 5 6 7]
[1. 2. 3. 4. 5. 6. 7.]
float64
[1.1 1.2 2.2 3.4 4.5 6.7]
[1 1 2 3 4 6]
int32
[1 3 0 5]
[ True  True False  True]
bool
[100   2   3   4   5]
[1 2 3 4 5]
[  1   2 200   4   5   6]
[  1   2 200   4   5   6]
None
[1 2 3 4 5 6]


### array reshaping

In [113]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [114]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.dtype)

[1 2 3 4 5 6]
int32


In [115]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
int32


In [121]:
arr = np.array([11,12,13,14,15])
print(arr)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)

[11 12 13 14 15]
int32
int32
int32
int32


In [122]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7]
int32


In [128]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
int32
int32
int32
int32
int32


arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(arr)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)

In [138]:
arr =np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
int32


### 3 -d array

In [140]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7 8]
int32


In [146]:
arr = np.array([11,22,33,44,55,66,77,88,99])
print(arr)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
print(arr.dtype)
pr

[11 22 33 44 55 66 77 88 99]
int32
int32
int32
int32
int32


### array reshaping

In [169]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.size)
print(arr.shape)
newarr = arr.reshape(6,2)
print(newarr)
print(newarr.ndim)
print(arr)
print(arr.ndim)

12
(12,)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
2
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [168]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
x = arr.reshape(4,4)
y = arr.reshape(16,1)
z = arr.reshape(8,2)
a = arr.reshape(4,2,2)
b = arr.reshape(2,4,2)
print(x)
print(y)
print(z)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1
(16,)
16
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


### array unkonwn dimension

In [173]:
arr = np.array([1,2,3,4,5,6,7,8])
x = arr.reshape(8,-1)
y = arr.reshape(4,2,-1)
z = arr.reshape(2,-1,2)
print(x)
print(y)
print(z)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array flattening


In [180]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim)
print(arr.shape)
x = arr.reshape(-1)
print(x)
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
[1 2 3 4 5 6 7 8]
(8,)


### numpy array iterating

In [184]:
# iterating for 1 - d array
arr = np.array([1,2,3])
print(arr)
print(arr.ndim)
for i in arr:
    print(i)

[1 2 3]
1
1
2
3


In [187]:
# iterating for 2 - d array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim)
for x in arr:
    print(x)
    print(x.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2
[1 2 3 4]
1
[5 6 7 8]
1


In [188]:
# iterating scalar element of 2 -d array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
for x in arr:
    print(x)
    for y in x:
        print(y)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8


In [193]:
# iterating 3 - d array
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr,'\n')
for x in arr:
    print(x,'\n')
    for y in x:
        print(y,'\n')
        for z in y:
            print(z)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

[[1 2 3 4]
 [5 6 7 8]] 

[1 2 3 4] 

1
2
3
4
[5 6 7 8] 

5
6
7
8
[[ 9 10 11 12]
 [13 14 15 16]] 

[ 9 10 11 12] 

9
10
11
12
[13 14 15 16] 

13
14
15
16


In [27]:
import numpy as np
arr = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[0])
print(arr[1])
print(arr[1:,3:])
print(arr[0:2])
print(arr[0:3,:2])
print(arr[:,[0,-1]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[5 6 7 8]
[[ 8]
 [12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [17]:
print(arr)
arr<2
arr * arr
arr*2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [37]:
arr = np.array([[1,2,3,4,5,6,7,8,9]])
print(arr)
print(arr.ndim)
x = arr.reshape(3,1,3)
y = arr.reshape(9)
z = arr.reshape(9,1)
print(x)
print(y)
print(z)


[[1 2 3 4 5 6 7 8 9]]
2
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [38]:
arr = np.array([1,2,3,4,5,6,7,8])
x = arr.reshape(-1)
print(x)

[1 2 3 4 5 6 7 8]


In [43]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = arr.reshape(1,-1,10)
print(x)

[[[ 1  2  3  4  5  6  7  8  9 10]]]


In [44]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [53]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    
    for y in x:
        print(y)

1
2
3
4
5
6
7
8


In [54]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for x in arr:
    
    for y in x:
       
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [57]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)
for x in arr:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8
[[ 9 10 11 12]
 [13 14 15 16]]
[ 9 10 11 12]
9
10
11
12
[13 14 15 16]
13
14
15
16


### iterating array using nditer()

In [7]:
# iterating on 3 - d array
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
y =   np.nditer(arr)

for x in y:
    print(x)

1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [12]:
arr = np.array([1,2,3])
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
    print(x)
for x in np.nditer(arr,flags = ['buffered'], op_dtypes = ['U']):
    print(x)
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['float']):
    print(x)
for x in np.nditer(arr,flags = ['buffered'], op_dtypes = ['int']):
    print(x)

b'1'
b'2'
b'3'
1
2
3
1.0
2.0
3.0
1
2
3


In [13]:
import numpy as np
np.__version__

'1.25.2'

In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [16]:
l = [1,2,3,4,5,6]
arr = np.array(l)
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [20]:
tup = (1,2,3,4,5,6,7,8,9)
arr = np.array(tup)
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1


In [21]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [22]:
arr = np.array(200)
print(arr)
print(arr.ndim)

200
0


In [23]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [24]:
arr = np.array([[1,2,3,4,5,6,7]])
print(arr)
print(arr.ndim)

[[1 2 3 4 5 6 7]]
2


In [25]:
arr = np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]]]
3


In [34]:
# access 1 - d array
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)
print(arr[4])
print(arr[-1])
print(arr[3])
print(arr[0])

[10 20 30 40 50]
1
50
50
40
10


In [46]:
# access 2 - d array
arr = ([1,2,3,4,5],[6,7,8,9,10])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(ar[0])
print(ar[1])
print(ar[0][2])
print(ar[1][4:])
print(ar[0][4:])
print(ar[0,2])
print(ar[1,4:])
print(ar[1,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[1 2 3 4 5]
[ 6  7  8  9 10]
3
[10]
[5]
3
[10]
7


In [62]:
# access 3 - d array
arr = ([[[11,22,33,44],[55,66,77,88]],[[99,100,110,120],[130,140,150,160]]])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(ar[0])
print(ar[1])
print(ar[0][0])
print(ar[0][1][0])
print(ar[1][0][3])
print(ar[0,0,1])
print(ar[0,0,3])
print(ar[1,1,2])

[[[ 11  22  33  44]
  [ 55  66  77  88]]

 [[ 99 100 110 120]
  [130 140 150 160]]]
3
[[11 22 33 44]
 [55 66 77 88]]
[[ 99 100 110 120]
 [130 140 150 160]]
[11 22 33 44]
55
120
22
44
150


In [63]:
a = np.array(0)
b = np.array([1,2,3,4])
c = np.array([[11,22,33,44]])
d = np.array([[[10,20,30,40,50]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [64]:
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)

[[[[[1 2 3 4 5]]]]]


In [92]:
# numpy array slicing
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.ndim)
print(len(arr))
print(arr[0:8])
print(arr[0:])
print(arr[0:5])
print(arr[-1])
print(arr[8])
print(arr[3:])
print(arr[:5])
print(arr[-4:-1])
print(arr[-8:-5])
print(arr[1:8:2])
print(arr[3:8:4])
print(arr[::2])
print(arr[1::2])
print(arr[5::3])



[1 2 3 4 5 6 7 8 9]
1
9
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
9
9
[4 5 6 7 8 9]
[1 2 3 4 5]
[6 7 8]
[2 3 4]
[2 4 6 8]
[4 8]
[1 3 5 7 9]
[2 4 6 8]
[6 9]


In [148]:
# numpy array slicing on 2 -d array
arr = ([[1,2,3,4,5],[6,7,8,9,10]])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(ar[0])
print(ar[1])
print(ar[:1])
print(ar[0,2:5])
print(ar[1,2:])
print(ar[0:,2:5])
print(ar[1,3:5])
print(ar[1,2])
print(ar[:,2:5])
print(ar[0,2:])
print(ar[0:1,2:4])
print(ar[0:,1:3])
print(ar[0:,0:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[1 2 3 4 5]
[ 6  7  8  9 10]
[[1 2 3 4 5]]
[3 4 5]
[ 8  9 10]
[[ 3  4  5]
 [ 8  9 10]]
[ 9 10]
8
[[ 3  4  5]
 [ 8  9 10]]
[3 4 5]
[[3 4]]
[[2 3]
 [7 8]]
[[1 2 3]
 [6 7 8]]


In [181]:
# slicing 3 - d array
arr = ([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
ar = np.array(arr)
print(type(ar))
print(ar.ndim)
print(ar[0])
print(ar[1])
print(ar[0:,1:])
print(ar[:1])
print(ar[1:4,1:2])
print(ar[0])
print(ar[0,1])
print(ar[0,0])
print(ar[0,1:3])

<class 'numpy.ndarray'>
3
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[[ 5  6  7  8]]

 [[13 14 15 16]]]
[[[1 2 3 4]
  [5 6 7 8]]]
[[[13 14 15 16]]]
[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]
[1 2 3 4]
[[5 6 7 8]]


In [182]:
# data types
# int
arr = np.array([1,2,3,4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [183]:
arr = np.array([1.1,2.2,3.3,4.4])
print(arr)
print(arr.dtype)

[1.1 2.2 3.3 4.4]
float64


In [184]:
arr = np.array(['apple','liwi','lemon','mango'])
print(arr)
print(arr.dtype)

['apple' 'liwi' 'lemon' 'mango']
<U5


In [185]:
arr = np.array(['aa','bb','cc','dd','ee'])
print(arr)
print(arr.dtype)

['aa' 'bb' 'cc' 'dd' 'ee']
<U2


In [197]:
arr = np.array([1,2,3,4,5], dtype = 'i')
print(arr)
print(arr.dtype)
arr = np.array([[1,2,3,4,5,6]],dtype = 'int')
print(arr)
print(arr.dtype)
arr = np.array([[[10,20,30,40,50,60]]], dtype = 'float')
print(arr)
print(arr.dtype)
arr = np.array([11,22,33,44,55,66,77], dtype = 'i8')
print(arr)
print(arr.dtype)
arr = np.array([11,22,33,44,55,66,77], dtype = 'i4')
print(arr)
print(arr.dtype)
arr = np.array([11,22,33,44,55,66,77], dtype = 'i2')
print(arr)
print(arr.dtype)
arr = np.array(['1','2','3','4'],dtype = 'int')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32
[[1 2 3 4 5 6]]
int32
[[[10. 20. 30. 40. 50. 60.]]]
float64
[11 22 33 44 55 66 77]
int64
[11 22 33 44 55 66 77]
int32
[11 22 33 44 55 66 77]
int16
[1 2 3 4]
int32


In [202]:
# data type conversion
# int to float
arr = np.array([1,2,3,4,5,6])
x = arr.astype('float')
print(arr)
print(x)
print(x.dtype)
arr = np.array([10,20,30,40,50])
a = arr.astype('bool')
print(arr)
print(a)
print(a.dtype)
a = np.array([1.1,2.2,3.3,4.4,5.5])
y = arr.astype('int')
print(a)
print(y)
print(y.dtype)
arr = np.array(['1','2','3','4','5','6'])
z = arr.astype('float')
print(arr)
print(z)
print(z.dtype)

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
float64
[10 20 30 40 50]
[ True  True  True  True  True]
bool
[1.1 2.2 3.3 4.4 5.5]
[10 20 30 40 50]
int32
['1' '2' '3' '4' '5' '6']
[1. 2. 3. 4. 5. 6.]
float64


In [203]:
# copy
arr = np.array([1,2,3,4,5,6,7])
x = arr.copy()
x[0] = 100
print(arr)
print(x)


[1 2 3 4 5 6 7]
[100   2   3   4   5   6   7]


In [206]:
# view
arr = np.array([10,20,30,40,50])
s = arr.view()
s[0] = 100
print(arr)
print(s)


[100  20  30  40  50]
[100  20  30  40  50]


In [207]:
# base
arr = np.array([1,2,3,4,5,6,7,8,9])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5 6 7 8 9]


In [216]:
# array reshaping
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.shape)
print(arr.size)
x = arr.reshape(9,1)
print(x)
y = arr.reshape(9)
print(y)
z = arr.reshape(3,3,1)
print(z)


[1 2 3 4 5 6 7 8 9]
(9,)
9
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [223]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
print(arr)
print(arr.shape)
print(arr.size)
a = arr.reshape(-1)
print(a)
b = arr.reshape(12)
print(b)
c = arr.reshape(4,3,1)
print(c)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [226]:
arr = np.array([[[1,2,3,4,5,6,7,8,9]]])
print(arr)
print(arr.shape)
print(arr.size)
a = arr.reshape(9)
print(a)
b = arr.reshape(3,3)
print(b)
c = arr.reshape(9,1)
print(c)

[[[1 2 3 4 5 6 7 8 9]]]
(1, 1, 9)
9
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [238]:
# unknown dimensions
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = arr.reshape(10,-1)
print(x)
y = arr.reshape(5,-1,2)
print(y)
z = arr.reshape(10)
print(z)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]]
[ 1  2  3  4  5  6  7  8  9 10]


In [232]:
arr = np.array([1,2,3,4,5,6,7,8])
x = arr.reshape(8,-1)
y = arr.reshape(4,2,-1)
z = arr.reshape(2,-1,2)
print(x)
print(y)
print(z)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [243]:
# flattening an array
arr = np.array([[[1,2,3,4,5,6,7,8,9,10]]])
print(arr)
a = arr.reshape(-1)
b = arr.reshape(-10)
print(b)
print(a)
print(a.shape)

[[[ 1  2  3  4  5  6  7  8  9 10]]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [244]:
# numpy array iterating
arr = np.array([1,2,3,4,5,6,7])
print(arr)
for x in arr:
    print(x)

[1 2 3 4 5 6 7]
1
2
3
4
5
6
7


In [245]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10]])
print(arr)
for x in arr:
    print(x)
    for y in x:
        print(y)

[[ 1  2  3  4  5  6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10


In [247]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
for x in arr:
    print(x)
    for y in x:
        print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
1
2
3
4
5
[ 6  7  8  9 10]
6
7
8
9
10


In [248]:
arr = np.array([[[1,2,3,4,5,6,7,8,9]]])
print(arr)
for x in arr:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[[[1 2 3 4 5 6 7 8 9]]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9


In [252]:
# iterating array using nditer()
arr = np.array([1,2,3,4,5,6,7,8,9])
for x in np.nditer(arr):
    print(x)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for y in np.nditer(arr):
    print(y)
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 
for z in np.nditer(arr):
    print(z)
    

1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8


In [258]:
# casting array element from one type to another type
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
    print(x)
for y in np.nditer(arr,flags = ['buffered'], op_dtypes = ['U']):
    print(y)
for z in np.nditer(arr, flags = ['buffered'], op_dtypes = ['float']):
    print(z)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
1
2
3
4
5
6
7
8
9
10
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [4]:
# 2 -d array slicing
import numpy as np
arr = ([[10,20,30],[40,50,60],[70,80,90]])
ar = np.array(arr)
print(ar,'\n')
print(ar[:2])

[[10 20 30]
 [40 50 60]
 [70 80 90]] 

[[10 20 30]
 [40 50 60]]


In [9]:
arr = ([[1,2,3],[4,5,6],[7,8,9]])
ar = np.array(arr)
print(ar,'\n')
print(ar[:2,1:3])
print(ar[1:,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


In [15]:
arr = ([[[1,2],[4,5]]])
ar =np.array(arr)
print(ar)
print(ar[0,1,1])

[[[1 2]
  [4 5]]]
5


In [24]:
a = np.array([1,2,3,4,5,6,7])
print(a)
print(a[1:5])
print(a[1:])
print(a[:1])
print(a[:5])
print(a[0:5])
print(a[1:5:2])
print(a[2:5:2])

[1 2 3 4 5 6 7]
[2 3 4 5]
[2 3 4 5 6 7]
[1]
[1 2 3 4 5]
[1 2 3 4 5]
[2 4]
[3 5]


In [41]:
a = ([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
ar = np.array(a)
print(ar)
print(ar[1,2:])
print(ar[::,2])
print(ar[:,3])
print(ar[:2,2])
print(ar[1:,4])
print(ar[:3,0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 8  9 10]
[ 3  8 13]
[ 4  9 14]
[3 8]
[10 15]
[ 1  6 11]


In [46]:
arr = ([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
ar = np.array(arr)
print(ar)
print(ar)
print(ar)
print(ar)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
